{"name": "test_unsuccessful_login_сourier_wrong_data[login]", "status": "passed", "parameters": [{"name": "wrong_data_in_body", "value": "'login'"}], "start": 1725230516826, "stop": 1725230516988, "uuid": "6eebcaa2-9b4b-4151-9ef3-ea00ae10e74a", "historyId": "af8e51c87b052fe951a96717247721f7", "testCaseId": "bcff023f2d8977ca35556b15aff8b439", "fullName": "tests.test_2_login_courier.TestLoginCourier#test_unsuccessful_login_сourier_wrong_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_2_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "sv-laptop"}, {"name": "thread", "value": "17742-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_2_login_courier"}]}