{"name": "test_unsuccessful_login_сourier_wrong_data[password]", "status": "passed", "parameters": [{"name": "wrong_data_in_body", "value": "'password'"}], "start": 1725230517155, "stop": 1725230517320, "uuid": "e1c4fb18-81a2-43aa-9440-71bc3ba6f304", "historyId": "b86d3cd644e150e1861f466c4b074e82", "testCaseId": "bcff023f2d8977ca35556b15aff8b439", "fullName": "tests.test_2_login_courier.TestLoginCourier#test_unsuccessful_login_сourier_wrong_data", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_2_login_courier"}, {"name": "subSuite", "value": "TestLoginCourier"}, {"name": "host", "value": "sv-laptop"}, {"name": "thread", "value": "17742-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_2_login_courier"}]}